[package]
name = "rimed"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.150"
rand = "0.8.5"
serde = { version = "1.0.192", features = [ "derive" ] }
serde_json = "1.0.108"
xdg = "2.5.2"
