#!/bin/sh
set -x
set -e
find src -name '*.c' | xargs clang-format --dry-run
export RUSTFLAGS='--deny warnings'
cargo fmt --check
cargo test --target-dir target/pre-commit
cargo test --target-dir target/pre-commit -- --ignored --test-threads=1
