#!/bin/sh
set -x
set -e
find src -name '*.c' | xargs clang-check -p build/meson
find src -name '*.c' | xargs clang-format --dry-run
cargo fmt --check
cargo check
cargo test
cargo test -- --ignored --test-threads=1
